apiVersion: v1
kind: Pod
metadata:
  name: bad-pod-no-reqs-limits
  namespace: default
  labels:
    app: api
    environment: dev
spec:
  containers:
    - name: bad-pod-no-reqs-limits
      image: api:v1
      ports:
        - containerPort: 8080
      ## нет resources
      livenessProbe:
        httpGet:
          path: /health
          port: 8080
      readinessProbe:
        httpGet:
          path: /health
          port: 8080
      securityContext:
        runAsNonRoot: true
        privileged: false