api:
  replicas: 6
  image: api:v4
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "3000m"
      memory: "150Mi"

worker:
  replicas: 4
  image: worker:v2
  port: 8081
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "3000m"
      memory: "150Mi"