apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  instances: 3
  storage:
    size: 1Gi
  bootstrap:
    initdb:
      database: lab3
      owner: lab3-user        
      secret:
        name: postgres-app-secret